# Generated by Django 4.1.4 on 2022-12-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
