# Generated by Django 4.1.4 on 2022-12-21 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_todo_is_finished_alter_todo_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'todos', 'verbose_name_plural': 'todo'},
        ),
    ]
